In [2]:
import numpy as np

In [4]:
# Creating Matrix
A = [[1,4,5],
    [-5,8,9]]

A

[[1, 4, 5], [-5, 8, 9]]

In [5]:

# Creating Matrix with Numpy 
B = np.array([[1,2,3],[3,4,5]])

B


array([[1, 2, 3],
       [3, 4, 5]])

In [6]:

# Creating a Numpy Matrix Filled with 0's

arrayOne =np.zeros( (2,3) )

arrayOne

array([[0., 0., 0.],
       [0., 0., 0.]])

In [7]:
# Creating a Numpy Matrix Filled with 1's

arrayOne =np.ones( (1,5) )

arrayOne

array([[1., 1., 1., 1., 1.]])